### ISSUE TITLE
ModuleNotFoundError: No module named 'lib'

### ISSUE THREAD

**Issue by lucious7** [n0nSmoker/SQLAlchemy-serializer#1]
I added the lib to my requirements.txt and installed it using `pip -r`. When I try to run my flask app I got this error:

```
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from app.routes import *
  File "/home/lucivaldo/Desenvolvimento/python_apis/parentesco-api/app/routes/__init__.py", line 3, in <module>
    from app.dao.ParentescoDao import ParentescoDao
  File "/home/lucivaldo/Desenvolvimento/python_apis/parentesco-api/app/dao/ParentescoDao.py", line 1, in <module>
    from app.models.Parentesco import Parentesco
  File "/home/lucivaldo/Desenvolvimento/python_apis/parentesco-api/app/models/Parentesco.py", line 3, in <module>
    from sqlalchemy_serializer import SerializerMixin
  File "/home/lucivaldo/.local/lib/python3.6/site-packages/sqlalchemy_serializer/__init__.py", line 1, in <module>
    from .serializer import SerializerMixin, Serializer
  File "/home/lucivaldo/.local/lib/python3.6/site-packages/sqlalchemy_serializer/serializer.py", line 9, in <module>
    from lib.timezones import to_local_time, format_date, format_datetime
ModuleNotFoundError: No module named 'lib'
```
I'm using SQLAlchemy-serializer 0.6, SQLAlchemy 1.1.15, Flask 0.12.2 and python 3

**Comment by barrycarey** [comment]
Lib is missing from the PIP package.  It's not an external package, it's supposed to be part of the package installed by PIP but it's not there.

**Comment by n0nSmoker** [comment]
Sorry for delay
