### ISSUE TITLE
pip install SQLAlchemy-serializer does not work

### ISSUE THREAD

**Issue by lightforever** [n0nSmoker/SQLAlchemy-serializer#9]
```
Collecting SQLAlchemy-serializer
  Using cached https://files.pythonhosted.org/packages/07/dc/bd77ce9bddf561c4eeb82103795c96f6c83e52469ca73c48790dfb6841dc/SQLAlchemy-serializer-1.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-l8bsyi_q/SQLAlchemy-serializer/setup.py", line 6, in <module>
        with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-l8bsyi_q/SQLAlchemy-serializer/README.md'

```

**Comment by n0nSmoker** [comment]
Thanks for your feedback! I deleted that logic, everything should be ok now!
